In [1]:
import numpy as np
import pandas as pd
from sklearn.cluster import KMeans

D:\App\Anaconda3\Lib\site-packages\pandas\core\computation\expressions.py:22: UserWarning: Pandas requires version '2.10.2' or newer of 'numexpr' (version '2.8.7' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
D:\App\Anaconda3\Lib\site-packages\pandas\core\arrays\masked.py:56: UserWarning: Pandas requires version '1.4.2' or newer of 'bottleneck' (version '1.3.7' currently installed).
  from pandas.core import (

In [2]:
pd.set_option('display.max_columns', None)
pd.set_option('display.float_format', lambda x: '%.7f' % x)

In [5]:
main_df = pd.read_csv("./../output/metric_df.csv")
df = main_df[['admin_name', 'A', 'admin_name.1', 'B', 'A_intersect_B', 'A_intersect_B_perimeter', 'A_union_B', 'metric_2', 'metric_3', 'metric_4', 'metric_5', 'pair']]
df.rename(columns={
    'A_intersect_B': 'inter_area',
    'A_intersect_B_perimeter': 'inter_peri',
    'metric_2': 'inter_area/A_union_B',
    'metric_3': 'inter_area/min',
    'metric_4': 'inter_area/max',
    'metric_5': 'inter_area/peri_sq',
}, inplace=True)

# convert to kilo
df['A'] = df['A']/(1000 ** 2)
df['B'] = df['B']/(1000 ** 2)
df['inter_area'] = df['inter_area']/(1000 ** 2)
df['A_union_B'] = df['A_union_B']/(1000 ** 2)
df['norm_inter_area'] = (df['inter_area'] - df['inter_area'].min()) / (df['inter_area'].max() - df['inter_area'].min())

df[['log_inter_area', 'log_iou', 'log_min', 'log_max', 'log_ap']] = np.log10(
    df[['inter_area', 'inter_area/A_union_B', 'inter_area/min', 'inter_area/max', 'inter_area/peri_sq']] + 1e-20
)
df.head()

,admin_name,A,admin_name.1,B,inter_area,inter_peri,A_union_B,inter_area/A_union_B,inter_area/min,inter_area/max,inter_area/peri_sq,pair,norm_inter_area,log_inter_area,log_iou,log_min,log_max,log_ap
0,bagerhat sadar,271.7185840,bagerhat sadar,271.7185840,271.7185840,7838179959.9434099,271.7185840,1.0000000,1.0000000,1.0000000,0.0346660,91_01,0.1533154,2.4341193,0.0000000,0.0000000,0.0000000,-1.4600959
1,chitalmari,140.2997346,bagerhat sadar,271.7185840,0.0000000,240667989.8338990,412.0183186,0.0000000,0.0000000,0.0000000,0.0000000,91_01,0.0000000,-10.2670862,-12.8820027,-12.4141430,-12.7012055,-12.6485045
2,fakirhat,163.4760642,bagerhat sadar,271.7185840,0.0000000,380796796.3964480,435.1946482,0.0000000,0.0000000,0.0000000,0.0000000,91_01,0.0000000,-10.2590977,-12.8977812,-12.4725519,-12.6932170,-12.8397910
3,kachua,115.5453690,bagerhat sadar,271.7185840,0.0000000,1209889847.4721401,387.2639530,0.0000000,0.0000000,0.0000000,0.0000000,91_01,0.0000000,-9.9182511,-12.5062582,-11.9810037,-12.3523704,-13.0009969
4,morrelganj,429.2820345,bagerhat sadar,271.7185840,0.0000000,36069194.2321772,701.0006185,0.0000000,0.0000000,0.0000000,0.0000000,91_01,0.0000000,-11.4251640,-14.2708816,-13.8592830,-14.0579062,-12.9823004

In [7]:
# stable row identifier
df = df.copy()
df["row_id"] = np.arange(len(df))

log_cols = [
    "log_inter_area",
    "log_iou",
    "log_min",
    "log_max",
    "log_ap",
]

for col in log_cols:
    diff_col = f"diff_{col}"

    # sort by that log column only for calculating consecutive jumps
    temp = df[["row_id", col]].dropna().sort_values(col).copy()

    # difference from previous sorted value
    temp[diff_col] = temp[col].diff().abs()

    # write differences back to original dataframe rows
    df = df.merge(
        temp[["row_id", diff_col]],
        on="row_id",
        how="left"
    )

# df.drop(columns='row_id', inplace=True)

df.head()

,admin_name,A,admin_name.1,B,inter_area,inter_peri,A_union_B,inter_area/A_union_B,inter_area/min,inter_area/max,inter_area/peri_sq,pair,norm_inter_area,log_inter_area,log_iou,log_min,log_max,log_ap,row_id,diff_log_inter_area,diff_log_iou,diff_log_min,diff_log_max,diff_log_ap
0,bagerhat sadar,271.7185840,bagerhat sadar,271.7185840,271.7185840,7838179959.9434099,271.7185840,1.0000000,1.0000000,1.0000000,0.0346660,91_01,0.1533154,2.4341193,0.0000000,0.0000000,0.0000000,-1.4600959,0,0.0000615,0.0000000,0.0000000,0.0000000,0.0000800
1,chitalmari,140.2997346,bagerhat sadar,271.7185840,0.0000000,240667989.8338990,412.0183186,0.0000000,0.0000000,0.0000000,0.0000000,91_01,0.0000000,-10.2670862,-12.8820027,-12.4141430,-12.7012055,-12.6485045,1,0.0000000,0.0000000,0.0000000,0.0000000,0.0000000
2,fakirhat,163.4760642,bagerhat sadar,271.7185840,0.0000000,380796796.3964480,435.1946482,0.0000000,0.0000000,0.0000000,0.0000000,91_01,0.0000000,-10.2590977,-12.8977812,-12.4725519,-12.6932170,-12.8397910,2,0.0012144,0.0000000,0.0013680,0.0000000,0.0000000
3,kachua,115.5453690,bagerhat sadar,271.7185840,0.0000000,1209889847.4721401,387.2639530,0.0000000,0.0000000,0.0000000,0.0000000,91_01,0.0000000,-9.9182511,-12.5062582,-11.9810037,-12.3523704,-13.0009969,3,0.0004236,0.0000000,0.0000000,0.0000000,0.0029591
4,morrelganj,429.2820345,bagerhat sadar,271.7185840,0.0000000,36069194.2321772,701.0006185,0.0000000,0.0000000,0.0000000,0.0000000,91_01,0.0000000,-11.4251640,-14.2708816,-13.8592830,-14.0579062,-12.9823004,4,0.0000000,0.0000000,0.0013094,0.0000000,0.0000000

In [5]:
# df.to_csv('cleaned_metric_df.csv')

for col in log_cols:
    diff_col = f"diff_{col}"
    idx = df[diff_col].idxmax()
    print(col, idx, df.loc[idx, diff_col])

# log_inter_area has highest jump at #5555 but if you check it's a difference between
# 3.61e-17 -> 4.97e-22. This is essentially a jump between artifacts.
# Meanwhile the jump in #7777 is from 0.313473 -> 0.000963 which is likely to be real.

log_inter_area 5555 3.5363764845702867
log_iou 7730 2.9060486006288584
log_min 7730 2.951030997321432
log_max 7730 2.866024914216881
log_ap 7730 1.1871826360472437

In [9]:
# threshold checking

metric_map = {
    "inter_area": "log_inter_area",
    "inter_area/A_union_B": "log_iou",
    "inter_area/min": "log_min",
    "inter_area/max": "log_max",
    "inter_area/peri_sq": "log_ap",
}

thresholds = {}

for metric_col, log_col in metric_map.items():
    diff_col = f"diff_{log_col}"

    temp = df[["row_id", metric_col, log_col, diff_col]].dropna()
    temp = temp.sort_values(log_col)

    max_idx = temp[diff_col].idxmax()
    pos = temp.index.get_loc(max_idx)

    low = temp.iloc[pos - 1][metric_col]
    high = temp.iloc[pos][metric_col]

    thresholds[metric_col] = np.sqrt(low * high)

thresholds["inter_area"] = (0.313472877 + 0.000962589) / 2  # when sorted by inter_area: #7730 - #141's inter_area
print(thresholds)

{'inter_area': 0.157217733, 'inter_area/A_union_B': 2.6287047623914992e-05, 'inter_area/min': 5.633506111149167e-05, 'inter_area/max': 4.9359558401757653e-05, 'inter_area/peri_sq': 6.519156681304418e-05}

In [11]:
filtered_sets = {}

for metric_col, threshold in thresholds.items():
    filtered_sets[metric_col] = set(
        df.loc[df[metric_col] >= threshold, "row_id"]
    )

    print(
        metric_col,
        "threshold:", threshold,
        "rows kept:", len(filtered_sets[metric_col])
    )

inter_area threshold: 0.157217733 rows kept: 1660
inter_area/A_union_B threshold: 2.6287047623914992e-05 rows kept: 1660
inter_area/min threshold: 5.633506111149167e-05 rows kept: 1660
inter_area/max threshold: 4.9359558401757653e-05 rows kept: 1660
inter_area/peri_sq threshold: 6.519156681304418e-05 rows kept: 1682